# Generated by Django 3.0.8 on 2020-07-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_auto_20200728_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='anonymous_answers',
            field=models.BooleanField(default=False),
        ),
    ]
