# Generated by Django 3.0.7 on 2020-07-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0003_auto_20200729_1633'),
        ('polling', '0003_question_anonymous_answers'),
    ]

    operations = [
    ]
