# Generated by Django 3.0.7 on 2020-07-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0005_question_total_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_professor',
            field=models.BooleanField(default=False),
        ),
    ]
